name: "index-generate"
on:
  workflow_dispatch:
  schedule:
    # every sunday at 2:51
    - cron:  '51 2 * * 0'
jobs:
  pin-nixpkgs:
    name: Pin nixpkgs revision
    runs-on: ubuntu-latest
    steps:
    - name: Fetch nixpkgs revision
      run: curl https://api.github.com/repos/NixOS/nixpkgs/git/refs/heads/nixpkgs-unstable | jq .object.sha | tr -d \" > nixpkgs-revision.txt
    - name: Upload revision artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-nixpkgs-revision
        path: nixpkgs-revision.txt

  build-database:
    name: Build database
    runs-on: ubuntu-latest
    needs: pin-nixpkgs
    strategy:
      matrix:
        platform: [i686-linux, x86_64-linux, aarch64-linux, x86_64-darwin, aarch64-darwin]
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - name: Download revision artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact-nixpkgs-revision
    - name: Get nixpkgs revision
      id: revision
      run: echo "::set-output name=revision::$(<nixpkgs-revision.txt)"
    - name: Run nix-index
      run: nix shell github:usertam/nix-index -c nix-index --db ./${{ matrix.platform }} --nixpkgs https://github.com/NixOS/nixpkgs/tarball/${{ steps.revision.outputs.revision }} --system ${{ matrix.platform }} 2>&1 | grep -v '+ generating index'
    - name: Rename built index
      run: mv ${{ matrix.platform }}/files index-${{ matrix.platform }}
    - name: Upload index artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.platform }}
        path: index-${{ matrix.platform }}

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-database
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Move artifacts
      run: mv artifact-*/* .
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ steps.date.outputs.date }}
        tag_name: ${{ steps.date.outputs.date }}
        files: |
          index-i686-linux
          index-x86_64-linux
          index-aarch64-linux
          index-x86_64-darwin
          index-aarch64-darwin
          nixpkgs-revision.txt
